using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;

namespace WissenBakkal.WFA.UI
{
    public partial class frmKategoriPanel : DevExpress.XtraEditors.XtraForm
    {
        public frmKategoriPanel()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            WissenBakkal.DAL.EntityFramework.MyContext dbContext = new WissenBakkal.DAL.EntityFramework.MyContext();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.Categories.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    dataLayoutControl1.DataSource = dbContext.Categories.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }
    }
}